### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by Dopamiinee** [pxsx/All-In-One-Discord-Bot#2]
I can't execute an order. He is online, he tells me that the commands have been loaded but it is impossible to use them. It tells me that the application is no longer responding and I don't have any errors.

**Comment by pxsx** [comment]
try 
/reload misc feature:interactions

**Comment by pxsx** [comment]
that should fix these issues

**Comment by pxsx** [comment]
Do you need any help ?
Otherwise i close the Issue
